app:
  name: api-gateway
  env: dev
  port: 9000

services:
  auth:
    url: http://localhost:8080

cors:
  allowedOrigins:
    - http://localhost:3000   #configuration for possible frontend client
    - http://localhost:5173

circuitBreaker:
  timeoutMs: 5000
  errorThreshold: 50
  resetTimeoutMs: 10000