receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4317
      grpc:
        endpoint: 0.0.0.0:4318

  filelog:
    include:
      - /var/lib/docker/containers/*/*.log
    start_at: beginning

processors:
  batch:

  resource:
    attributes:
      - key: service.name
        from_attribute: service.name
        action: insert

exporters:

  otlp/elastic:
    endpoint: http://apm-server:8200
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlphttp/logstash:
    endpoint: http://logstash:5000

service:
  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/elastic]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logstash]