receivers:
  otlp:
    protocols:
      http:
      grpc:

  filelog:
    include:
      - /var/lib/docker/containers/*/*.log
    start_at: beginning
    operators:
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      - type: move
        from: log
        to: body
      - type: json_parser
        parse_from: body
        timestamp:
          parse_from: ts
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      - type: move
        from: message
        to: body
      - type: move
        from: stream
        to: attributes.container.stream
      - type: move
        from: container_id
        to: attributes.container.id

processors:
  batch:


exporters:
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp, filelog]
      processors: [batch]
      exporters: [otlphttp/loki]
