receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}

  transform/logs:
    log_statements:
      - context: log
        statements:
          - set(attributes["message"], body)
          - set(attributes["severity"], severity_text)
          - set(attributes["service"], resource.attributes["service.name"])
          - set(attributes["timestamp"], time)

  resource:
    attributes:
      - key: service.name
        from_attribute: service.name
        action: insert

exporters:

  otlp/elastic:
    endpoint: http://apm-server:8200
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  http/logstash:
    endpoint: http://logstash:5000

service:
  pipelines:

    traces:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [otlp/elastic]

    metrics:
      receivers: [otlp]
      processors: [resource, batch]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [transform/logs, batch]
      exporters: [http/logstash]