"""create usage tables

Revision ID: 20a7be7a5710
Revises: 
Create Date: 2026-02-15 15:47:11.763977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a7be7a5710'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_aggregates',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('daily_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('monthly_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('rolling_avg', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', 'metric')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_aggregates')
    # ### end Alembic commands ###
